---
  detectors:
    IrresponsibleModule:
      enabled: false
  exclude_paths:
    - _snippets
    - lib/project_info.rb # one-time test fixture creator
    - spec/spike-scripts # original scripts from week4 to collect data (before OOP)
