---
# Name your file secrets.yml

development:
  DB_FILENAME: db/local/dev.db
  SPOTIFY_CLIENT_ID: 'your_client_id'
  SPOTIFY_CLIENT_SECRET: 'your_client_secret'
  GPT_API_KEY: 'your_api_key'
  GOOGLE_CLIENT_KEY: "your_google_client_key"
  WORD_LIST_FILENAME: 'files/mandarin_word_list.yml'

test:
  DB_FILENAME: db/local/test.db
  SPOTIFY_CLIENT_ID: 'your_client_id'
  SPOTIFY_CLIENT_SECRET: 'your_client_secret'
  GPT_API_KEY: 'your_api_key'
  GOOGLE_CLIENT_KEY: "your_google_client_key"
  WORD_LIST_FILENAME: 'files/mandarin_word_list.yml'
  SESSION_SECRET: 'run rake new_session_secret'

production:
  # Assign DATABASE_URL in production
  SPOTIFY_CLIENT_ID: 'your_client_id'
  SPOTIFY_CLIENT_SECRET: 'your_client_secret'
  GPT_API_KEY: 'your_api_key'
  GOOGLE_CLIENT_KEY: "your_google_client_key"
  WORD_LIST_FILENAME: 'files/mandarin_word_list.yml'
  SESSION_SECRET: 'run rake new_session_secret'