---
development:
  API_HOST: http://localhost:9090
  APP_HOST: http://localhost:9000
  SESSION_SECRET: 
app_test:
  API_HOST: http://localhost:9090
  APP_HOST: http://localhost:9000

test:
  API_HOST: http://localhost:9090
  APP_HOST: http://localhost:9000
  SESSION_SECRET: 

production:
  API_HOST: http://url.to.api
  APP_HOST: http://url.to.app
  SESSION_SECRET:
