---
# Name your file secrets.yml

development:
  SPOTIFY_CLIENT_ID: 'your_client_id'
  SPOTIFY_CLIENT_SECRET: 'your_client'
  DB_FILENAME: db/local/dev.db

test:
  DB_FILENAME: db/local/test.db
  SPOTIFY_CLIENT_ID: 'your_client_id'
  SPOTIFY_CLIENT_SECRET: 'your_client'

production:
  SPOTIFY_CLIENT_ID: 'your_client_id'
  SPOTIFY_CLIENT_SECRET: 'your_client'